set_location_assignment PIN_AH27 -to HSMC2_SMSDA
set_location_assignment PIN_AC22 -to HSMC2_D1_P
set_location_assignment PIN_AC23 -to HSMC2_D1_N
set_location_assignment PIN_AG24 -to HSMC2_TX0_P
set_location_assignment PIN_AH24 -to HSMC2_TX0_N
set_location_assignment PIN_AG26 -to HSMC2_TX1
set_location_assignment PIN_AG28 -to HSMC2_SMSCL
set_location_assignment PIN_AF25 -to HSMC2_D2_P
set_location_assignment PIN_AG25 -to HSMC2_D2_N
set_location_assignment PIN_AD23 -to HSMC2_RX0_P
set_location_assignment PIN_AE22 -to HSMC2_RX0_N
set_location_assignment PIN_AG23 -to HSMC2_RX1_P
set_location_assignment PIN_AF23 -to HSMC2_RX1_N
set_location_assignment PIN_AH26 -to HSMC2_PRSNTN
