# TCL File Generated by Component Editor 20.1
# Mon Jul 26 11:53:55 BST 2021
# DO NOT MODIFY


# 
# oss_hal "OPS-SAT Swansea Hardware Abstraction Layer" v1.0
#  2021.07.26.11:53:55
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module oss_hal
# 
set_module_property DESCRIPTION ""
set_module_property NAME oss_hal
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME "OPS-SAT Swansea Hardware Abstraction Layer"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL oss_hal 
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
source ../../src/userLogic/files.tcl
add_fileset_file oss_hal.sv SYSTEM_VERILOG PATH ../../src/userLogic/oss_hal.sv TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock_sink
# 
add_interface clock_sink clock end
set_interface_property clock_sink clockRate 0
set_interface_property clock_sink ENABLED true
set_interface_property clock_sink EXPORT_OF ""
set_interface_property clock_sink PORT_NAME_MAP ""
set_interface_property clock_sink CMSIS_SVD_VARIABLES ""
set_interface_property clock_sink SVD_ADDRESS_GROUP ""

add_interface_port clock_sink hal_clk clk Input 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock_sink
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink hal_reset reset Input 1


# 
# connection point reg_itf
# 
add_interface reg_itf avalon end
set_interface_property reg_itf addressUnits WORDS
set_interface_property reg_itf associatedClock clock_sink
set_interface_property reg_itf associatedReset reset_sink
set_interface_property reg_itf bitsPerSymbol 8
set_interface_property reg_itf burstOnBurstBoundariesOnly false
set_interface_property reg_itf burstcountUnits WORDS
set_interface_property reg_itf explicitAddressSpan 0
set_interface_property reg_itf holdTime 0
set_interface_property reg_itf linewrapBursts false
set_interface_property reg_itf maximumPendingReadTransactions 0
set_interface_property reg_itf maximumPendingWriteTransactions 0
set_interface_property reg_itf readLatency 0
set_interface_property reg_itf readWaitTime 1
set_interface_property reg_itf setupTime 0
set_interface_property reg_itf timingUnits Cycles
set_interface_property reg_itf writeWaitTime 0
set_interface_property reg_itf ENABLED true
set_interface_property reg_itf EXPORT_OF ""
set_interface_property reg_itf PORT_NAME_MAP ""
set_interface_property reg_itf CMSIS_SVD_VARIABLES ""
set_interface_property reg_itf SVD_ADDRESS_GROUP ""

add_interface_port reg_itf reg_itf_addr_in address Input 16 
add_interface_port reg_itf reg_itf_read_in read Input 1
add_interface_port reg_itf reg_itf_write_in write Input 1
add_interface_port reg_itf reg_itf_readdata_out readdata Output 32
add_interface_port reg_itf reg_itf_writedata_in writedata Input 32
set_interface_assignment reg_itf embeddedsw.configuration.isFlash 0
set_interface_assignment reg_itf embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment reg_itf embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment reg_itf embeddedsw.configuration.isPrintableDevice 0

